# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-XML_RDB
version:      0.06
version_from: XML_RDB.pm
installdirs:  site
requires:
    DBI:                           1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
